name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./scripts/linuxGenerate.sh
    - name: make
      run: make && ./bin/Debug-linux-x86_64/CXML_Tests/CXML_Tests
